version: '3'
services: 
    dbcadastro:
        image: mongo
        environment: 
            MONGO_INITDB_ROOT_USERNAME: minhaOpn
            MONGO_INITDB_ROOT_PASSWORD: minhaOpn#@dev
        ports:
            - "27017:27017"
        volumes:
            - "/home/docker/minhaopiniao/dbcadastro:/data/db"
        networks:
            - minhaopn
    dbkong:
        image: postgres:9.6
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        ports: 
            - "5432:5432"
        networks: 
            - minhaopn